# bru-espresso — a lekker colorscheme
# https://github.com/kmf/bru
#
# Drop into ~/.config/kitty/themes/bru-espresso.conf
# Then in kitty.conf:  include ./themes/bru-espresso.conf

background            #1c1814
foreground            #f5e8c7
selection_background  #322b23
selection_foreground  #fbf3db

cursor                #dbb32d
cursor_text_color     #1c1814

url_color             #4695f7

active_border_color   #dbb32d
inactive_border_color #3a332b
bell_border_color     #fa5750

active_tab_background   #26211c
active_tab_foreground   #dbb32d
inactive_tab_background #1c1814
inactive_tab_foreground #8a7f6f
tab_bar_background      #1c1814

# normal
color0  #1c1814
color1  #fa5750
color2  #75b938
color3  #dbb32d
color4  #4695f7
color5  #f275be
color6  #41c7b9
color7  #f5e8c7

# bright
color8  #3a332b
color9  #ff665c
color10 #84c747
color11 #ebc13d
color12 #58a3ff
color13 #ff84cd
color14 #53d6c7
color15 #fbf3db

# extended
color16 #ed8649
color17 #af88eb
