# bru-espresso — foot terminal
# https://github.com/kmf/bru
#
# Install:
#   cp bru-espresso.ini ~/.config/foot/themes/bru-espresso
#   Then in ~/.config/foot/foot.ini:
#     [main]
#     include=~/.config/foot/themes/bru-espresso

[cursor]
color=1c1814 dbb32d

[colors]
foreground=f5e8c7
background=1c1814
selection-foreground=fbf3db
selection-background=322b23

regular0=1c1814
regular1=fa5750
regular2=75b938
regular3=dbb32d
regular4=4695f7
regular5=f275be
regular6=41c7b9
regular7=f5e8c7

bright0=3a332b
bright1=ff665c
bright2=84c747
bright3=ebc13d
bright4=58a3ff
bright5=ff84cd
bright6=53d6c7
bright7=fbf3db
